# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backup.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'backup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61\x63kup.proto\"Q\n\rBackupRequest\x12\x0f\n\x07\x63liente\x18\x01 \x01(\t\x12\x0e\n\x06\x63lasse\x18\x02 \x01(\t\x12\x0f\n\x07veiculo\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"%\n\x0e\x42\x61\x63kupResponse\x12\x13\n\x0b\x63onfirmacao\x18\x01 \x01(\t2?\n\x06\x42\x61\x63kup\x12\x35\n\x12RegistrarTransacao\x12\x0e.BackupRequest\x1a\x0f.BackupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKUPREQUEST']._serialized_start=16
  _globals['_BACKUPREQUEST']._serialized_end=97
  _globals['_BACKUPRESPONSE']._serialized_start=99
  _globals['_BACKUPRESPONSE']._serialized_end=136
  _globals['_BACKUP']._serialized_start=138
  _globals['_BACKUP']._serialized_end=201
# @@protoc_insertion_point(module_scope)
