# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heartbeat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'heartbeat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fheartbeat.proto\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x10HeartbeatRequest\x12\x0f\n\x07servico\x18\x01 \x01(\t\"!\n\rListaServicos\x12\x10\n\x08servicos\x18\x01 \x03(\t2\x85\x01\n\tHeartbeat\x12\x38\n\x0b\x45nviarSinal\x12\x11.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12>\n\x14ListarServicosAtivos\x12\x16.google.protobuf.Empty\x1a\x0e.ListaServicosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heartbeat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=48
  _globals['_HEARTBEATREQUEST']._serialized_end=83
  _globals['_LISTASERVICOS']._serialized_start=85
  _globals['_LISTASERVICOS']._serialized_end=118
  _globals['_HEARTBEAT']._serialized_start=121
  _globals['_HEARTBEAT']._serialized_end=254
# @@protoc_insertion_point(module_scope)
