# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: terminal.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'terminal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eterminal.proto\"g\n\x0eRentCarRequest\x12\x12\n\nID_cliente\x18\x01 \x01(\t\x12\x12\n\nIP_cliente\x18\x02 \x01(\t\x12\x15\n\rPorta_cliente\x18\x03 \x01(\t\x12\x16\n\x0e\x43lasse_veiculo\x18\x04 \x01(\t\"2\n\x0fRentCarResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"T\n\x10ReturnCarRequest\x12\x12\n\nID_cliente\x18\x01 \x01(\t\x12\x14\n\x0cNome_veiculo\x18\x02 \x01(\t\x12\x16\n\x0e\x43lasse_veiculo\x18\x03 \x01(\t\"$\n\x11ReturnCarResponse\x12\x0f\n\x07message\x18\x01 \x01(\x08\"*\n\x0f\x43\x61llbackMessage\x12\x17\n\x0fmessage_content\x18\x01 \x01(\t\"\"\n\x10\x43\x61llbackResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2r\n\x08Terminal\x12/\n\x08RentACar\x12\x0f.RentCarRequest\x1a\x10.RentCarResponse\"\x00\x12\x35\n\nReturnACar\x12\x11.ReturnCarRequest\x1a\x12.ReturnCarResponse\"\x00\x32I\n\x0f\x43\x61llbackService\x12\x36\n\x0fReceiveCallback\x12\x10.CallbackMessage\x1a\x11.CallbackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'terminal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RENTCARREQUEST']._serialized_start=18
  _globals['_RENTCARREQUEST']._serialized_end=121
  _globals['_RENTCARRESPONSE']._serialized_start=123
  _globals['_RENTCARRESPONSE']._serialized_end=173
  _globals['_RETURNCARREQUEST']._serialized_start=175
  _globals['_RETURNCARREQUEST']._serialized_end=259
  _globals['_RETURNCARRESPONSE']._serialized_start=261
  _globals['_RETURNCARRESPONSE']._serialized_end=297
  _globals['_CALLBACKMESSAGE']._serialized_start=299
  _globals['_CALLBACKMESSAGE']._serialized_end=341
  _globals['_CALLBACKRESPONSE']._serialized_start=343
  _globals['_CALLBACKRESPONSE']._serialized_end=377
  _globals['_TERMINAL']._serialized_start=379
  _globals['_TERMINAL']._serialized_end=493
  _globals['_CALLBACKSERVICE']._serialized_start=495
  _globals['_CALLBACKSERVICE']._serialized_end=568
# @@protoc_insertion_point(module_scope)
